{{- if eq (len .Values.operator.namespace) 0 }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: redis-operator
  apiGroup: rbac.authorization.k8s.io
